import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Forex Trading Signals — Live AI Signals | MarketSignals24',
  description:
    'Get real-time, AI-powered forex trading signals for EUR/USD, GBP/USD, USD/JPY and 30+ major pairs. Win rates up to 87%. Start free today.',
  keywords:
    'MarketSignals24, forex trading signals, live forex signals, AI forex signals, fx signals, forex alerts, EUR/USD signals, GBP/USD signals, best forex signals, accurate forex signals',
  alternates: {
    canonical: 'https://marketsignals24.com/forex-signals',
    languages: {
      'fr-FR': 'https://marketsignals24.com/fr/signaux-forex',
      'es-ES': 'https://marketsignals24.com/es/senales-forex',
      'de-DE': 'https://marketsignals24.com/de/forex-signale',
    },
  },
  openGraph: {
    title: 'Forex Trading Signals — Live AI Signals | MarketSignals24',
    description:
      'Real-time AI-powered forex signals. 30+ currency pairs. Up to 87% win rate. No experience needed.',
    url: 'https://marketsignals24.com/forex-signals',
    siteName: 'MarketSignals24',
    type: 'website',
  },
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What are forex trading signals?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Forex trading signals are real-time trade recommendations that tell you when to buy or sell a currency pair, at what price to enter, where to set your stop-loss, and where to take profit. At MarketSignals24, signals are generated by an AI engine that analyses price action, technical indicators, and market sentiment simultaneously.',
      },
    },
    {
      '@type': 'Question',
      name: 'How accurate are MarketSignals24 forex signals?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Our AI model has achieved win rates of up to 87% in live backtests across major pairs since 2023. Past performance is not a guarantee of future results, and all trading involves risk. We recommend using proper money management and never risking more than 1–2% of your capital per trade.',
      },
    },
    {
      '@type': 'Question',
      name: 'Which currency pairs do you cover?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'We cover all 8 major forex pairs (EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, NZD/USD, USD/CAD, EUR/GBP) plus 25+ cross pairs and exotic currencies including EUR/JPY, GBP/JPY, EUR/AUD, and more.',
      },
    },
    {
      '@type': 'Question',
      name: 'Do I need trading experience to use your signals?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. Each signal comes with a clear direction (BUY / SELL), entry price, stop-loss, and take-profit levels. Beginners can follow signals directly, while advanced traders can use them to confirm their own analysis.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I receive forex signals?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Signals appear instantly in your dashboard the moment the AI detects a qualifying setup. An audible alert fires in the browser so you never miss a trade. The platform also works as a Progressive Web App (PWA) so you can install it on your phone and receive signals anywhere.',
      },
    },
    {
      '@type': 'Question',
      name: 'What subscription plan do I need for forex signals?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Forex signals are included in all plans starting from the Pass 24h at €6. A Weekly Pass at €25 and a Monthly Pass at €85 offer the best value for regular traders. New users can start with a 24h pass to test the service risk-free.',
      },
    },
  ],
};

export default function ForexSignalsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <main className="min-h-screen bg-gray-950 text-white">
        {/* Hero */}
        <section className="relative overflow-hidden bg-gradient-to-br from-gray-900 via-gray-950 to-black py-20 px-4">
          <div className="absolute inset-0 bg-yellow-400/5 pointer-events-none" />
          <div className="max-w-4xl mx-auto text-center relative z-10">
            <span className="inline-block bg-yellow-400/10 border border-yellow-400/30 text-yellow-400 text-sm font-medium px-4 py-1 rounded-full mb-6">
              AI-Powered · Real-Time · 30+ Pairs
            </span>
            <h1 className="text-4xl md:text-5xl font-bold mb-6 leading-tight">
              Live <span className="text-yellow-400">Forex Trading Signals</span> Powered by AI
            </h1>
            <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
              Receive buy and sell alerts for EUR/USD, GBP/USD, USD/JPY and 30+ currency pairs the moment our AI detects a high-probability setup — complete with entry, stop-loss, and take-profit levels.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/register"
                className="bg-yellow-400 text-black font-bold px-8 py-4 rounded-xl hover:bg-yellow-300 transition-colors text-lg"
              >
                Start Free Today
              </Link>
              <Link
                href="/tarifs"
                className="bg-white/10 border border-white/20 text-white font-semibold px-8 py-4 rounded-xl hover:bg-white/20 transition-colors text-lg"
              >
                View Plans from €6
              </Link>
            </div>
          </div>
        </section>

        {/* Stats */}
        <section className="py-12 px-4 border-y border-white/10 bg-gray-900/50">
          <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {[
              { value: '87%', label: 'Win Rate (backtest)' },
              { value: '30+', label: 'Currency Pairs' },
              { value: '24/7', label: 'Signal Monitoring' },
              { value: '<1s', label: 'Signal Delivery' },
            ].map((stat) => (
              <div key={stat.label}>
                <p className="text-3xl font-bold text-yellow-400">{stat.value}</p>
                <p className="text-gray-400 text-sm mt-1">{stat.label}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Main Content */}
        <article className="max-w-4xl mx-auto px-4 py-16 space-y-12">

          <section>
            <h2 className="text-2xl font-bold mb-4">What Are Forex Trading Signals?</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Forex trading signals are precise, actionable trade recommendations delivered in real time. Each signal specifies a currency pair, a direction (BUY or SELL), an entry price, a stop-loss level to limit downside risk, and one or more take-profit targets to lock in gains. Instead of spending hours analysing charts yourself, you receive a ready-to-execute idea the moment a setup forms.
            </p>
            <p className="text-gray-300 leading-relaxed mb-4">
              At MarketSignals24, signals are not produced by human analysts who can be tired, emotional, or slow. They are generated by a proprietary AI engine that runs 24 hours a day, 7 days a week, scanning every tick of price data across all major and minor currency pairs simultaneously. The engine combines dozens of technical indicators — including RSI, MACD, Bollinger Bands, EMA crossovers, and support/resistance levels — with pattern-recognition algorithms trained on millions of historical trades.
            </p>
            <p className="text-gray-300 leading-relaxed">
              The result is a consistent, emotion-free feed of trade ideas that you can follow directly on the trading platform of your choice. Whether you use MetaTrader 4, MetaTrader 5, cTrader, or a broker's native app, our signals give you a clear edge.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">How Our AI Generates Forex Signals</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              The MarketSignals24 signal engine ingests tick-by-tick price data from multiple liquidity providers and processes it through a multi-layer analysis pipeline:
            </p>
            <div className="space-y-4">
              {[
                {
                  title: '1. Technical Analysis Layer',
                  text: 'The engine calculates over 40 indicators across multiple timeframes simultaneously (M5, M15, H1, H4, D1). Signals are only issued when indicators align across at least two timeframes, dramatically reducing false positives.',
                },
                {
                  title: '2. Pattern Recognition',
                  text: 'A convolutional model trained on historical candlestick data identifies high-probability patterns: double tops/bottoms, head-and-shoulders, bullish/bearish engulfing, pin bars, and breakout structures.',
                },
                {
                  title: '3. Volatility Filtering',
                  text: 'Before issuing a signal, the engine checks the Average True Range (ATR) to ensure the market has enough volatility for the trade to reach its target while staying below the stop-loss. Low-volatility "dead" market conditions are filtered out.',
                },
                {
                  title: '4. Risk-Reward Calculation',
                  text: 'Every signal is only published if the risk-reward ratio is at least 1:1.5. Most signals target a 1:2 or 1:2.5 ratio, meaning you risk €1 to potentially gain €2–2.50.',
                },
              ].map((item) => (
                <div key={item.title} className="bg-gray-900 border border-white/10 rounded-xl p-5">
                  <h3 className="font-semibold text-yellow-400 mb-2">{item.title}</h3>
                  <p className="text-gray-300 text-sm leading-relaxed">{item.text}</p>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Currency Pairs We Cover</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Our signal engine monitors more than 30 currency pairs around the clock:
            </p>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {['EUR/USD', 'GBP/USD', 'USD/JPY', 'USD/CHF', 'AUD/USD', 'NZD/USD', 'USD/CAD', 'EUR/GBP', 'EUR/JPY', 'GBP/JPY', 'EUR/AUD', 'EUR/CAD', 'AUD/JPY', 'CHF/JPY', 'GBP/AUD', 'GBP/CAD', 'AUD/CAD', 'AUD/NZD', 'NZD/JPY', 'EUR/NZD', 'USD/MXN', 'USD/SGD', 'USD/HKD', 'EUR/CHF', 'GBP/CHF'].map((pair) => (
                <div key={pair} className="bg-gray-900 border border-white/10 rounded-lg px-4 py-2 text-center font-mono text-yellow-400 text-sm">
                  {pair}
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">How to Use Forex Signals — Step by Step</h2>
            <ol className="space-y-4">
              {[
                { step: '1', title: 'Create your account', text: 'Sign up at MarketSignals24 in under 60 seconds — no credit card required for registration.' },
                { step: '2', title: 'Choose a subscription plan', text: 'Select the plan that matches your trading frequency. Start with Pass 24h (€6) to test the service, or grab the Monthly Pass (€85) for the best per-day value.' },
                { step: '3', title: 'Open your dashboard', text: 'Navigate to the Signals tab to see all active and recent forex signals. Each card displays the pair, direction, entry, SL, TP, and confidence score.' },
                { step: '4', title: 'Enable sound alerts', text: 'Click "Activate Sound Alerts" once to unlock browser audio. You will now hear a chime the moment a new signal appears — no need to stare at the screen.' },
                { step: '5', title: 'Execute the trade', text: 'Open the corresponding pair on your broker, enter at the signal price, and set the stop-loss and take-profit exactly as shown. Adjust lot size according to your own risk tolerance.' },
                { step: '6', title: 'Monitor and close', text: 'Most signals resolve within 1–24 hours. You can watch progress in real time via the Performance tab, which tracks your win rate and P&L history.' },
              ].map((item) => (
                <li key={item.step} className="flex gap-4 bg-gray-900 border border-white/10 rounded-xl p-5">
                  <span className="flex-shrink-0 w-8 h-8 rounded-full bg-yellow-400 text-black font-bold flex items-center justify-center text-sm">{item.step}</span>
                  <div>
                    <h3 className="font-semibold mb-1">{item.title}</h3>
                    <p className="text-gray-300 text-sm leading-relaxed">{item.text}</p>
                  </div>
                </li>
              ))}
            </ol>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Risk Management for Forex Signal Traders</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Even the most accurate signal service cannot eliminate risk. All forex trading involves the possibility of losing money, and you should never trade with funds you cannot afford to lose. Here are the risk management principles we recommend to all MarketSignals24 users:
            </p>
            <ul className="space-y-3 text-gray-300">
              {[
                'Never risk more than 1–2% of your account on a single trade, regardless of the signal confidence level.',
                'Always use the stop-loss provided in the signal. Moving or removing a stop-loss is the most common reason traders blow accounts.',
                'Do not over-leverage. A leverage ratio of 1:20 to 1:50 is appropriate for most retail forex traders.',
                'Diversify across pairs. Do not enter multiple highly correlated trades (e.g., EUR/USD and GBP/USD both long) simultaneously.',
                'Keep a trading journal. Note which signals you followed and the outcome to refine your personal strategy.',
              ].map((tip) => (
                <li key={tip} className="flex gap-3">
                  <span className="text-yellow-400 mt-1 flex-shrink-0">✓</span>
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
            <p className="text-amber-400 text-sm mt-4 p-4 bg-amber-400/10 border border-amber-400/20 rounded-xl">
              ⚠️ CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. Between 74–89% of retail investor accounts lose money when trading CFDs. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.
            </p>
          </section>

          {/* Internal links */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Explore Other Signal Types</h2>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <Link href="/crypto-signals" className="block bg-gray-900 border border-white/10 rounded-xl p-5 hover:border-yellow-400/50 transition-colors group">
                <h3 className="font-semibold group-hover:text-yellow-400 transition-colors">Crypto Signals →</h3>
                <p className="text-gray-400 text-sm mt-1">BTC, ETH, and 20+ altcoins</p>
              </Link>
              <Link href="/binary-options-signals" className="block bg-gray-900 border border-white/10 rounded-xl p-5 hover:border-yellow-400/50 transition-colors group">
                <h3 className="font-semibold group-hover:text-yellow-400 transition-colors">Binary Options Signals →</h3>
                <p className="text-gray-400 text-sm mt-1">1–5 min OTC signals, 24/7</p>
              </Link>
              <Link href="/ai-trading-signals" className="block bg-gray-900 border border-white/10 rounded-xl p-5 hover:border-yellow-400/50 transition-colors group">
                <h3 className="font-semibold group-hover:text-yellow-400 transition-colors">AI Signals →</h3>
                <p className="text-gray-400 text-sm mt-1">How our AI engine works</p>
              </Link>
            </div>
          </section>

          {/* FAQ */}
          <section>
            <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
            <div className="space-y-4">
              {faqSchema.mainEntity.map((item) => (
                <div key={item.name} className="bg-gray-900 border border-white/10 rounded-xl p-5">
                  <h3 className="font-semibold mb-2 text-yellow-400">{item.name}</h3>
                  <p className="text-gray-300 text-sm leading-relaxed">{item.acceptedAnswer.text}</p>
                </div>
              ))}
            </div>
          </section>

          {/* CTA */}
          <section className="text-center bg-gradient-to-br from-yellow-400/10 to-yellow-400/5 border border-yellow-400/20 rounded-2xl p-10">
            <h2 className="text-2xl font-bold mb-3">Ready to Trade with an Edge?</h2>
            <p className="text-gray-300 mb-6">Join thousands of traders receiving live AI forex signals every day.</p>
            <Link
              href="/register"
              className="inline-block bg-yellow-400 text-black font-bold px-10 py-4 rounded-xl hover:bg-yellow-300 transition-colors text-lg"
            >
              Create Free Account
            </Link>
          </section>
        </article>
      </main>
    </>
  );
}
